"""Adapter: canonical registry -> OpenAI Codex CLI layout.

Emits:
  dist/codex/AGENTS.md               aggregated router/index (the cross-tool standard)
  dist/codex/.codex/agents/<name>.md per-agent prompt (full body)
  dist/codex/.codex/skills/<name>/   skill directories (SKILL.md standard), copied

Read/copy only; never executes content.
"""
from __future__ import annotations

from pathlib import Path

from . import common

TOOL = "codex"


def emit(items: list[common.Item], out_root: Path) -> dict:
    root = out_root / TOOL
    adir = root / ".codex" / "agents"
    sdir = root / ".codex" / "skills"
    adir.mkdir(parents=True, exist_ok=True)
    sdir.mkdir(parents=True, exist_ok=True)

    agents = [i for i in items if i.kind == "agent"]
    skills = [i for i in items if i.kind == "skill"]

    for it in agents:
        dest = common.safe_join(adir, common.slug(it.name) + ".md")
        header = f"# {it.name}\n\n_{it.description}_\n\n"
        dest.write_text(header + it.body.lstrip("\n"), encoding="utf-8")
    for it in skills:
        common.copy_tree_confined(it.path, common.safe_join(sdir, common.slug(it.name)))

    lines = ["# AGENTS.md", "",
             "Aggregated agents and skills (generated by agent-forge). This file is the",
             "cross-tool entry point; full agent prompts live in `.codex/agents/` and",
             "skills in `.codex/skills/`.", ""]
    by_domain: dict[str, list] = {}
    for it in agents:
        by_domain.setdefault(it.domain or "general", []).append(it)
    lines.append("## Agents")
    for dom in sorted(by_domain):
        lines.append(f"\n### {dom}")
        for it in sorted(by_domain[dom], key=lambda x: x.name):
            lines.append(f"- **{it.name}** — {it.description} "
                         f"(`.codex/agents/{common.slug(it.name)}.md`)")
    if skills:
        lines.append("\n## Skills")
        for it in sorted(skills, key=lambda x: x.name):
            lines.append(f"- **{it.name}** — {it.description} "
                         f"(`.codex/skills/{common.slug(it.name)}/`)")
    lines.append("")
    (root / "AGENTS.md").write_text("\n".join(lines), encoding="utf-8")
    return {"tool": TOOL, "agents": len(agents), "skills": len(skills), "root": str(root)}
