"""Adapter: canonical registry -> Gemini CLI layout.

Emits:
  dist/gemini/GEMINI.md                  index/router (hierarchical context file)
  dist/gemini/.gemini/agents/<name>.md   per-agent prompt (full body)
  dist/gemini/.gemini/commands/<name>.toml  custom slash-command per agent
  dist/gemini/.gemini/skills/<name>/     skill directories, copied

Read/copy only; never executes content.
"""
from __future__ import annotations

from pathlib import Path

from . import common

TOOL = "gemini"


def _toml_command(it: common.Item) -> str:
    desc = it.description.replace('"', '\\"')
    prompt = it.body.lstrip("\n").replace('"""', '\\"\\"\\"')
    return (f'description = "{desc}"\n'
            f'prompt = """\n{prompt}\n"""\n')


def emit(items: list[common.Item], out_root: Path) -> dict:
    root = out_root / TOOL
    adir = root / ".gemini" / "agents"
    cdir = root / ".gemini" / "commands"
    sdir = root / ".gemini" / "skills"
    for d in (adir, cdir, sdir):
        d.mkdir(parents=True, exist_ok=True)

    agents = [i for i in items if i.kind == "agent"]
    skills = [i for i in items if i.kind == "skill"]

    for it in agents:
        common.safe_join(adir, common.slug(it.name) + ".md").write_text(
            f"# {it.name}\n\n_{it.description}_\n\n" + it.body.lstrip("\n"),
            encoding="utf-8")
        common.safe_join(cdir, common.slug(it.name) + ".toml").write_text(
            _toml_command(it), encoding="utf-8")
    for it in skills:
        common.copy_tree_confined(it.path, common.safe_join(sdir, common.slug(it.name)))

    lines = ["# GEMINI.md", "",
             "Agents and skills available to Gemini CLI (generated by agent-forge).",
             "Each agent is also exposed as a custom command under `.gemini/commands/`",
             f"(invoke with `/{'{name}'}`). Skills live in `.gemini/skills/`.", "",
             "## Agents"]
    for it in sorted(agents, key=lambda x: (x.domain, x.name)):
        lines.append(f"- `/{common.slug(it.name)}` — {it.description}")
    if skills:
        lines.append("\n## Skills")
        for it in sorted(skills, key=lambda x: x.name):
            lines.append(f"- **{it.name}** — {it.description}")
    lines.append("")
    (root / "GEMINI.md").write_text("\n".join(lines), encoding="utf-8")
    return {"tool": TOOL, "agents": len(agents), "skills": len(skills), "root": str(root)}
